# Comprehensive Ethics Audit Configuration
# Full-scale professional audit with all advanced features enabled

# General audit settings
audit_components:
  - "bias"
  - "safety"

parallel_execution: true
max_workers: 4
log_level: "DEBUG"
enable_progress_tracking: true
save_intermediate_results: true

# Taxonomy settings
taxonomy_path: null  # Will use default comprehensive taxonomy
custom_taxonomy: {}

# Supported model types
supported_model_types:
  - "sklearn"
  - "pytorch"
  - "tensorflow"
  - "huggingface"
  - "custom"
  - "xgboost"
  - "lightgbm"
  - "catboost"

# Comprehensive bias detection configuration
bias:
  # All major protected attributes
  protected_attributes:
    - "race"
    - "gender"
    - "age"
    - "religion"
    - "disability"
    - "sexual_orientation"
    - "ethnicity"
    - "nationality"
    - "socioeconomic_status"
    - "education_level"
  
  # All available fairness metrics
  fairness_metrics:
    - "demographic_parity"
    - "equalized_odds"
    - "calibration"
    - "individual_fairness"
    - "predictive_parity"
    - "treatment_equality"
  
  # Strict statistical thresholds
  significance_threshold: 0.01  # More stringent
  bias_threshold: 0.05  # Strict bias tolerance
  
  # Enhanced sample requirements
  min_sample_size: 200
  bootstrap_samples: 2000  # High precision
  
  # Advanced analysis enabled
  intersectional_analysis: true
  temporal_analysis: true

# Comprehensive safety scanning configuration
safety:
  # All vulnerability tests
  vulnerability_tests:
    - "adversarial_examples"
    - "data_poisoning"
    - "model_inversion"
    - "membership_inference"
    - "prompt_injection"
    - "output_manipulation"
  
  # Thorough adversarial testing
  adversarial_epsilon: 0.1
  adversarial_iterations: 100  # Comprehensive testing
  adversarial_step_size: 0.001  # Fine-grained steps
  
  # Extensive robustness testing
  noise_levels:
    - 0.001
    - 0.005
    - 0.01
    - 0.05
    - 0.1
    - 0.2
    - 0.3
  robustness_samples: 2000  # Comprehensive sampling
  
  # Strict safety thresholds
  safety_threshold: 0.8  # High safety requirement
  max_attack_success_rate: 0.05  # Very low tolerance
  
  # Enhanced privacy parameters
  privacy_budget: 0.5  # Stricter privacy requirement
  k_anonymity: 10  # High anonymity requirement

# Professional report configuration
report:
  # Multiple output formats
  formats:
    - "html"
    - "json"
  
  # Full content options
  include_visualizations: true
  include_raw_data: true  # Complete data inclusion
  include_recommendations: true
  detailed_explanations: true  # Comprehensive explanations
  
  # Professional styling
  theme: "professional"
  color_scheme: "default"
  
  # Professional output settings
  output_directory: "comprehensive_audit_reports"
  filename_template: "comprehensive_audit_{timestamp}_{model_name}"

# Advanced configuration options
advanced:
  # Cross-validation settings
  cross_validation_folds: 5
  stratified_sampling: true
  
  # Bootstrap confidence intervals
  confidence_level: 0.95
  bootstrap_confidence_intervals: true
  
  # Statistical power analysis
  statistical_power_analysis: true
  effect_size_thresholds:
    small: 0.2
    medium: 0.5
    large: 0.8
  
  # Advanced metrics
  calculate_auc_metrics: true
  calculate_partial_dependence: true
  feature_importance_analysis: true
  
  # Monitoring and alerting
  performance_monitoring: true
  alert_thresholds:
    bias_score: 0.1
    safety_score: 0.7
    violation_count: 5
  
  # Export options
  export_raw_metrics: true
  export_statistical_tests: true
  export_confidence_intervals: true
  
  # Compliance frameworks
  compliance_frameworks:
    - "EU_AI_Act"
    - "GDPR"
    - "IEEE_2857"
    - "ISO_23053"
    - "NIST_AI_RMF"
  
  # Quality assurance
  duplicate_analysis_check: true
  cross_validator_agreement: true
  inter_rater_reliability: true